// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contracts

import "encoding/json"
import "fmt"
import "reflect"
import "time"

type ChannelType string

const ChannelTypeFacebook ChannelType = "facebook"
const ChannelTypeInstagram ChannelType = "instagram"
const ChannelTypeTelegram ChannelType = "telegram"
const ChannelTypeWaOfficial ChannelType = "wa_official"
const ChannelTypeWaUnofficial ChannelType = "wa_unofficial"

var enumValues_ChannelType = []interface{}{
	"wa_official",
	"wa_unofficial",
	"instagram",
	"facebook",
	"telegram",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ChannelType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ChannelType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ChannelType, v)
	}
	*j = ChannelType(v)
	return nil
}

// Sumber kebenaran event schema antar servis (lihat docs/prd/09-api-contracts.md).
// Edit di sini lalu `make contracts`.
type EventsSchemaJson struct {
	// Inbound corresponds to the JSON schema field "inbound".
	Inbound *InboundMessage `json:"inbound,omitempty,omitzero" yaml:"inbound,omitempty" mapstructure:"inbound,omitempty"`

	// Outbound corresponds to the JSON schema field "outbound".
	Outbound *OutboundCommand `json:"outbound,omitempty,omitzero" yaml:"outbound,omitempty" mapstructure:"outbound,omitempty"`

	// Realtime corresponds to the JSON schema field "realtime".
	Realtime *RealtimeEvent `json:"realtime,omitempty,omitzero" yaml:"realtime,omitempty" mapstructure:"realtime,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status *MessageStatus `json:"status,omitempty,omitzero" yaml:"status,omitempty" mapstructure:"status,omitempty"`
}

// Stream message.inbound (Gateway -> Engine).
type InboundMessage struct {
	// Body corresponds to the JSON schema field "body".
	Body InboundMessageBody `json:"body,omitempty,omitzero" yaml:"body,omitempty" mapstructure:"body,omitempty"`

	// ChannelId corresponds to the JSON schema field "channel_id".
	ChannelId string `json:"channel_id" yaml:"channel_id" mapstructure:"channel_id"`

	// ChannelType corresponds to the JSON schema field "channel_type".
	ChannelType ChannelType `json:"channel_type" yaml:"channel_type" mapstructure:"channel_type"`

	// <channel_id>:<provider_message_id>
	DedupKey string `json:"dedup_key" yaml:"dedup_key" mapstructure:"dedup_key"`

	// ulid
	EventId string `json:"event_id" yaml:"event_id" mapstructure:"event_id"`

	// From corresponds to the JSON schema field "from".
	From Party `json:"from" yaml:"from" mapstructure:"from"`

	// Media corresponds to the JSON schema field "media".
	Media interface{} `json:"media,omitempty,omitzero" yaml:"media,omitempty" mapstructure:"media,omitempty"`

	// ProviderMessageId corresponds to the JSON schema field "provider_message_id".
	ProviderMessageId string `json:"provider_message_id" yaml:"provider_message_id" mapstructure:"provider_message_id"`

	// Timestamp corresponds to the JSON schema field "timestamp".
	Timestamp time.Time `json:"timestamp" yaml:"timestamp" mapstructure:"timestamp"`

	// Type corresponds to the JSON schema field "type".
	Type InboundMessageType `json:"type" yaml:"type" mapstructure:"type"`
}

type InboundMessageBody *string

type InboundMessageType string

const InboundMessageTypeFile InboundMessageType = "file"
const InboundMessageTypeImage InboundMessageType = "image"
const InboundMessageTypeInteractive InboundMessageType = "interactive"
const InboundMessageTypeText InboundMessageType = "text"

var enumValues_InboundMessageType = []interface{}{
	"text",
	"image",
	"file",
	"interactive",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InboundMessageType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InboundMessageType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InboundMessageType, v)
	}
	*j = InboundMessageType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InboundMessage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channel_id"]; raw != nil && !ok {
		return fmt.Errorf("field channel_id in InboundMessage: required")
	}
	if _, ok := raw["channel_type"]; raw != nil && !ok {
		return fmt.Errorf("field channel_type in InboundMessage: required")
	}
	if _, ok := raw["dedup_key"]; raw != nil && !ok {
		return fmt.Errorf("field dedup_key in InboundMessage: required")
	}
	if _, ok := raw["event_id"]; raw != nil && !ok {
		return fmt.Errorf("field event_id in InboundMessage: required")
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in InboundMessage: required")
	}
	if _, ok := raw["provider_message_id"]; raw != nil && !ok {
		return fmt.Errorf("field provider_message_id in InboundMessage: required")
	}
	if _, ok := raw["timestamp"]; raw != nil && !ok {
		return fmt.Errorf("field timestamp in InboundMessage: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in InboundMessage: required")
	}
	type Plain InboundMessage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = InboundMessage(plain)
	return nil
}

type Media struct {
	// Filename corresponds to the JSON schema field "filename".
	Filename MediaFilename `json:"filename,omitempty,omitzero" yaml:"filename,omitempty" mapstructure:"filename,omitempty"`

	// Mime corresponds to the JSON schema field "mime".
	Mime string `json:"mime" yaml:"mime" mapstructure:"mime"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url" yaml:"url" mapstructure:"url"`
}

type MediaFilename *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Media) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["mime"]; raw != nil && !ok {
		return fmt.Errorf("field mime in Media: required")
	}
	if _, ok := raw["url"]; raw != nil && !ok {
		return fmt.Errorf("field url in Media: required")
	}
	type Plain Media
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Media(plain)
	return nil
}

// Stream message.status (Gateway -> Engine).
type MessageStatus struct {
	// Error corresponds to the JSON schema field "error".
	Error MessageStatusError `json:"error,omitempty,omitzero" yaml:"error,omitempty" mapstructure:"error,omitempty"`

	// IdempotencyKey corresponds to the JSON schema field "idempotency_key".
	IdempotencyKey string `json:"idempotency_key" yaml:"idempotency_key" mapstructure:"idempotency_key"`

	// ProviderMessageId corresponds to the JSON schema field "provider_message_id".
	ProviderMessageId *string `json:"provider_message_id,omitempty,omitzero" yaml:"provider_message_id,omitempty" mapstructure:"provider_message_id,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status MessageStatusStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Timestamp corresponds to the JSON schema field "timestamp".
	Timestamp time.Time `json:"timestamp" yaml:"timestamp" mapstructure:"timestamp"`
}

type MessageStatusError *string

type MessageStatusStatus string

const MessageStatusStatusDelivered MessageStatusStatus = "delivered"
const MessageStatusStatusFailed MessageStatusStatus = "failed"
const MessageStatusStatusRead MessageStatusStatus = "read"
const MessageStatusStatusSent MessageStatusStatus = "sent"

var enumValues_MessageStatusStatus = []interface{}{
	"sent",
	"delivered",
	"read",
	"failed",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageStatusStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MessageStatusStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MessageStatusStatus, v)
	}
	*j = MessageStatusStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MessageStatus) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["idempotency_key"]; raw != nil && !ok {
		return fmt.Errorf("field idempotency_key in MessageStatus: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in MessageStatus: required")
	}
	if _, ok := raw["timestamp"]; raw != nil && !ok {
		return fmt.Errorf("field timestamp in MessageStatus: required")
	}
	type Plain MessageStatus
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MessageStatus(plain)
	return nil
}

// Stream message.outbound (Engine -> Gateway).
type OutboundCommand struct {
	// Body corresponds to the JSON schema field "body".
	Body OutboundCommandBody `json:"body,omitempty,omitzero" yaml:"body,omitempty" mapstructure:"body,omitempty"`

	// ChannelId corresponds to the JSON schema field "channel_id".
	ChannelId string `json:"channel_id" yaml:"channel_id" mapstructure:"channel_id"`

	// ConversationId corresponds to the JSON schema field "conversation_id".
	ConversationId string `json:"conversation_id" yaml:"conversation_id" mapstructure:"conversation_id"`

	// ulid
	EventId string `json:"event_id" yaml:"event_id" mapstructure:"event_id"`

	// gateway skip kalau sudah kirim
	IdempotencyKey string `json:"idempotency_key" yaml:"idempotency_key" mapstructure:"idempotency_key"`

	// Media corresponds to the JSON schema field "media".
	Media interface{} `json:"media,omitempty,omitzero" yaml:"media,omitempty" mapstructure:"media,omitempty"`

	// Template corresponds to the JSON schema field "template".
	Template *OutboundCommandTemplate `json:"template,omitempty,omitzero" yaml:"template,omitempty" mapstructure:"template,omitempty"`

	// To corresponds to the JSON schema field "to".
	To Party `json:"to" yaml:"to" mapstructure:"to"`

	// Type corresponds to the JSON schema field "type".
	Type OutboundCommandType `json:"type" yaml:"type" mapstructure:"type"`
}

type OutboundCommandBody *string

type OutboundCommandTemplate struct {
	// Components corresponds to the JSON schema field "components".
	Components []interface{} `json:"components,omitempty,omitzero" yaml:"components,omitempty" mapstructure:"components,omitempty"`

	// Lang corresponds to the JSON schema field "lang".
	Lang *string `json:"lang,omitempty,omitzero" yaml:"lang,omitempty" mapstructure:"lang,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type OutboundCommandType string

const OutboundCommandTypeMedia OutboundCommandType = "media"
const OutboundCommandTypeTemplate OutboundCommandType = "template"
const OutboundCommandTypeText OutboundCommandType = "text"

var enumValues_OutboundCommandType = []interface{}{
	"text",
	"template",
	"media",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OutboundCommandType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OutboundCommandType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_OutboundCommandType, v)
	}
	*j = OutboundCommandType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OutboundCommand) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channel_id"]; raw != nil && !ok {
		return fmt.Errorf("field channel_id in OutboundCommand: required")
	}
	if _, ok := raw["conversation_id"]; raw != nil && !ok {
		return fmt.Errorf("field conversation_id in OutboundCommand: required")
	}
	if _, ok := raw["event_id"]; raw != nil && !ok {
		return fmt.Errorf("field event_id in OutboundCommand: required")
	}
	if _, ok := raw["idempotency_key"]; raw != nil && !ok {
		return fmt.Errorf("field idempotency_key in OutboundCommand: required")
	}
	if _, ok := raw["to"]; raw != nil && !ok {
		return fmt.Errorf("field to in OutboundCommand: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in OutboundCommand: required")
	}
	type Plain OutboundCommand
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = OutboundCommand(plain)
	return nil
}

type Party struct {
	// ExternalId corresponds to the JSON schema field "external_id".
	ExternalId string `json:"external_id" yaml:"external_id" mapstructure:"external_id"`

	// Name corresponds to the JSON schema field "name".
	Name PartyName `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Phone corresponds to the JSON schema field "phone".
	Phone PartyPhone `json:"phone,omitempty,omitzero" yaml:"phone,omitempty" mapstructure:"phone,omitempty"`
}

type PartyName *string

type PartyPhone *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Party) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["external_id"]; raw != nil && !ok {
		return fmt.Errorf("field external_id in Party: required")
	}
	type Plain Party
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Party(plain)
	return nil
}

// Pub/Sub realtime.<tenant_id> (Engine -> Web via Gateway WS).
type RealtimeEvent struct {
	// Payload corresponds to the JSON schema field "payload".
	Payload RealtimeEventPayload `json:"payload" yaml:"payload" mapstructure:"payload"`

	// Type corresponds to the JSON schema field "type".
	Type RealtimeEventType `json:"type" yaml:"type" mapstructure:"type"`
}

type RealtimeEventPayload map[string]interface{}

type RealtimeEventType string

const RealtimeEventTypeChannelStatus RealtimeEventType = "channel.status"
const RealtimeEventTypeConversationAssigned RealtimeEventType = "conversation.assigned"
const RealtimeEventTypeConversationUpdated RealtimeEventType = "conversation.updated"
const RealtimeEventTypeMessageNew RealtimeEventType = "message.new"

var enumValues_RealtimeEventType = []interface{}{
	"message.new",
	"conversation.updated",
	"conversation.assigned",
	"channel.status",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RealtimeEventType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RealtimeEventType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RealtimeEventType, v)
	}
	*j = RealtimeEventType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RealtimeEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in RealtimeEvent: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in RealtimeEvent: required")
	}
	type Plain RealtimeEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = RealtimeEvent(plain)
	return nil
}
