package social

import "errors"

var (
	ErrAccountNotFound         = errors.New("social account not found")
	ErrJobNotFound             = errors.New("social job not found")
	ErrRuleNotFound            = errors.New("auto-reply rule not found")
	ErrIncomingEventNotFound   = errors.New("incoming social event not found")
	ErrAccountBusy             = errors.New("social account is already in use")
	ErrAccountNotConnected     = errors.New("social account is not connected")
	ErrUnsupportedPlatform     = errors.New("unsupported social platform")
	ErrUnsupportedAction       = errors.New("unsupported social action")
	ErrAutomationNotReady      = errors.New("social browser automation is not implemented yet")
	ErrInvalidTargetURL        = errors.New("target URL does not match the account platform")
	ErrContentRequired         = errors.New("comment content is required")
	ErrAccountActionRequired   = errors.New("social account requires manual action")
	ErrSessionExpired          = errors.New("social session expired")
	ErrLoginRequired           = errors.New("social login required")
	ErrCaptcha                 = errors.New("social captcha detected")
	ErrCheckpoint              = errors.New("social checkpoint detected")
	ErrSuspiciousLogin         = errors.New("social suspicious login detected")
	ErrConfirmIdentity         = errors.New("social identity confirmation required")
	ErrTemporaryBlock          = errors.New("social account temporarily blocked")
	ErrRateLimited             = errors.New("social account rate limited")
	ErrCommentNotFound         = errors.New("social comment not found")
	ErrConversationNotFound    = errors.New("social conversation not found")
	ErrPrivateReplyUnavailable = errors.New("social private reply unavailable")
	ErrReplyFailed             = errors.New("social reply failed")
	ErrElementNotFound         = errors.New("social element not found")
	ErrNavigationFailed        = errors.New("social navigation failed")
)
