/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ChannelType = "wa_official" | "wa_unofficial" | "instagram" | "facebook" | "telegram";

/**
 * Sumber kebenaran event schema antar servis (lihat docs/prd/09-api-contracts.md). Edit di sini lalu `make contracts`.
 */
export interface ChatCepatEvents {
  inbound?: InboundMessage;
  outbound?: OutboundCommand;
  status?: MessageStatus;
  realtime?: RealtimeEvent;
  [k: string]: unknown;
}
/**
 * Stream message.inbound (Gateway -> Engine).
 */
export interface InboundMessage {
  /**
   * ulid
   */
  event_id: string;
  /**
   * <channel_id>:<provider_message_id>
   */
  dedup_key: string;
  channel_id: string;
  channel_type: ChannelType;
  from: Party;
  type: "text" | "image" | "file" | "interactive";
  body?: string | null;
  media?: Media | null;
  provider_message_id: string;
  timestamp: string;
  [k: string]: unknown;
}
export interface Party {
  external_id: string;
  phone?: string | null;
  name?: string | null;
  [k: string]: unknown;
}
export interface Media {
  url: string;
  mime: string;
  filename?: string | null;
  [k: string]: unknown;
}
/**
 * Stream message.outbound (Engine -> Gateway).
 */
export interface OutboundCommand {
  /**
   * ulid
   */
  event_id: string;
  /**
   * gateway skip kalau sudah kirim
   */
  idempotency_key: string;
  channel_id: string;
  to: Party;
  type: "text" | "template" | "media";
  body?: string | null;
  template?: {
    name?: string;
    lang?: string;
    components?: unknown[];
    [k: string]: unknown;
  } | null;
  media?: Media | null;
  conversation_id: string;
  [k: string]: unknown;
}
/**
 * Stream message.status (Gateway -> Engine).
 */
export interface MessageStatus {
  idempotency_key: string;
  provider_message_id?: string;
  status: "sent" | "delivered" | "read" | "failed";
  error?: string | null;
  timestamp: string;
  [k: string]: unknown;
}
/**
 * Pub/Sub realtime.<tenant_id> (Engine -> Web via Gateway WS).
 */
export interface RealtimeEvent {
  type: "message.new" | "conversation.updated" | "conversation.assigned" | "channel.status";
  payload: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
