# generated by datamodel-codegen:
#   filename:  events.schema.json
#   timestamp: 2026-06-16T06:40:59+00:00

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field


class Party(BaseModel):
    external_id: str
    phone: str | None = None
    name: str | None = None


class Media(BaseModel):
    url: str
    mime: str
    filename: str | None = None


class ChannelType(Enum):
    wa_official = 'wa_official'
    wa_unofficial = 'wa_unofficial'
    instagram = 'instagram'
    facebook = 'facebook'
    telegram = 'telegram'


class Type(Enum):
    text = 'text'
    image = 'image'
    file = 'file'
    interactive = 'interactive'


class InboundMessage(BaseModel):
    event_id: str = Field(..., description='ulid')
    dedup_key: str = Field(..., description='<channel_id>:<provider_message_id>')
    channel_id: UUID
    channel_type: ChannelType
    from_: Party = Field(..., alias='from')
    type: Type
    body: str | None = None
    media: Media | None = None
    provider_message_id: str
    timestamp: AwareDatetime


class Type1(Enum):
    text = 'text'
    template = 'template'
    media = 'media'


class Template(BaseModel):
    name: str | None = None
    lang: str | None = None
    components: list[Any] | None = None


class OutboundCommand(BaseModel):
    event_id: str = Field(..., description='ulid')
    idempotency_key: str = Field(..., description='gateway skip kalau sudah kirim')
    channel_id: UUID
    to: Party
    type: Type1
    body: str | None = None
    template: Template | None = None
    media: Media | None = None
    conversation_id: UUID


class Status(Enum):
    sent = 'sent'
    delivered = 'delivered'
    read = 'read'
    failed = 'failed'


class MessageStatus(BaseModel):
    idempotency_key: str
    provider_message_id: str | None = None
    status: Status
    error: str | None = None
    timestamp: AwareDatetime


class Type2(Enum):
    message_new = 'message.new'
    conversation_updated = 'conversation.updated'
    conversation_assigned = 'conversation.assigned'
    channel_status = 'channel.status'


class RealtimeEvent(BaseModel):
    type: Type2
    payload: dict[str, Any]


class ChatCepatEvents(BaseModel):
    inbound: InboundMessage | None = None
    outbound: OutboundCommand | None = None
    status: MessageStatus | None = None
    realtime: RealtimeEvent | None = None
